apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: todo-app
spec:
  selector:
    app: todo-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP

